inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 20 # Please modify!
    n_positions: 11

training:
    data: int
    task: dp_lis
    task_kwargs: {}
    data_kwargs: {"low": 1, "high": 40}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        dims:
            start: 20
            end: 20
            inc: 1
            interval: 2000
        points:
            start: 1
            end: 1
            inc: 2
            interval: 2000

out_dir: ../models/lis

wandb:
    name: "lis"
