inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 1 # Please modify!
    n_positions: 21

# test_run: true
training:
    resume_id: 943b8308-13a9-41ac-82fe-b728572453f8
    data: int
    task: dp_lis
    task_kwargs: {}
    data_kwargs: {"low": 1, "high": 40, "resort": true}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 10000
    keep_every_steps: 40000
    train_steps: 500001
    curriculum:
        dims:
            start: 1
            end: 1
            inc: 1
            interval: 2000
        points:
            start: 20
            end: 20
            inc: 2
            interval: 2000

out_dir: ../models/lis_new

wandb:
    name: "lis_new"
